tarball=exceptiongroup-VERSION-py3-none-any.whl
sha1=e69c438e6d15111c4f7cc18224b31a42a58663da
sha256=4bfd3996ac73b41e9b9628b04e079f193850720ea5945fc96a08633c66912f14
md5=d252c64173c449dc34654e7be8211744
cksum=527795480
upstream_url=https://pypi.io/packages/py3/e/exceptiongroup/exceptiongroup-VERSION-py3-none-any.whl
